version: '3.8'
services:
  web:
    build: ./crue
    volumes:
      - .:/app
    command: gunicorn crue.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./crue/.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
