# Generated by Django 5.0.3 on 2024-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("nom", models.CharField(max_length=200)),
                ("riviere", models.CharField(max_length=100)),
                ("hauteur_max", models.FloatField()),
                ("debit_max", models.FloatField()),
                ("date_max", models.DateField()),
                ("hauteur", models.FloatField()),
                ("debit", models.FloatField()),
                ("date_hauteur", models.DateField()),
                ("niveau_alerte", models.IntegerField()),
                ("date_alerte", models.DateField()),
            ],
        ),
    ]
