# Generated by Django 5.0.3 on 2024-03-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
