# Generated by Django 5.0.3 on 2024-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0002_station_latitude_station_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="date_max",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="debit_max",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="hauteur_max",
            field=models.FloatField(null=True),
        ),
    ]
