# Generated by Django 5.0.3 on 2024-03-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0004_alter_station_date_max_alter_station_debit_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="date_hauteur",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="debit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="hauteur",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
