# Generated by Django 5.0.3 on 2024-03-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0005_alter_station_date_hauteur_alter_station_debit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="code",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name="RepereCrue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("presentation_crue", models.TextField(blank=True, null=True)),
                ("contexte", models.TextField(blank=True, null=True)),
                ("impact_humain_urbain", models.TextField(blank=True, null=True)),
                ("photo1", models.URLField(blank=True, null=True)),
                ("photo2", models.URLField(blank=True, null=True)),
                ("photo3", models.URLField(blank=True, null=True)),
                ("videos", models.URLField(blank=True, null=True)),
                ("en_savoir_plus", models.URLField(blank=True, null=True)),
                (
                    "code_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reperes_crues",
                        to="civicmap.station",
                        to_field="code",
                    ),
                ),
            ],
        ),
    ]
