# Generated by Django 5.0.3 on 2024-03-18 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0006_alter_station_code_reperecrue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vigicrue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niveau_alerte", models.IntegerField(unique=True)),
                ("time", models.CharField(max_length=20)),
                ("main_color", models.CharField(max_length=20)),
                ("color_4", models.CharField(max_length=20)),
                ("color_3", models.CharField(max_length=20)),
                ("color_2", models.CharField(max_length=20)),
                ("color_1", models.CharField(max_length=20)),
                ("text", models.CharField(max_length=20)),
                ("full_text", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="station",
            name="niveau_alerte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station",
                to="civicmap.vigicrue",
                to_field="niveau_alerte",
            ),
        ),
    ]
