# Generated by Django 5.0.3 on 2024-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0007_vigicrue_alter_station_niveau_alerte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="date_alerte",
            field=models.DateField(blank=True, null=True),
        ),
    ]
