# Generated by Django 5.0.3 on 2024-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0008_alter_station_date_alerte"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reperecrue",
            old_name="videos",
            new_name="video1",
        ),
        migrations.AddField(
            model_name="reperecrue",
            name="video2",
            field=models.URLField(blank=True, null=True),
        ),
    ]
