# Generated by Django 5.0.3 on 2024-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0009_rename_videos_reperecrue_video1_reperecrue_video2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reperecrue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
