# Generated by Django 5.0.3 on 2024-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("civicmap", "0010_alter_reperecrue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reperecrue",
            name="id_gsheet",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
