name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
    
    - name: Deploy to VPS
      env:
        DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
        LOGIN: ${{ secrets.LOGIN }}
        IP: ${{ secrets.IP }}
      run: |
        sshpass -p $DEPLOY_PASS ssh -o StrictHostKeyChecking=no $LOGIN@$IP 'bash -s' < deploy_script.sh
